---
sidebar: sidebar 
permalink: set-up-upgrade-health-checker.html 
keywords: upgrade, health, checker, set up, download 
summary: 'Vous pouvez télécharger Upgrade Health Checker pour générer des rapports complets sur site avant de passer à une version plus récente d"ONTAP.' 
---
= Téléchargez et configurez Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez télécharger Upgrade Health Checker pour générer des rapports complets sur site avant de passer à une version plus récente d'ONTAP.

.À propos de cette tâche
Upgrade Health Checker prend en charge les mises à niveau pour les versions ONTAP sur site 9.11.1 et ultérieures. Si vous utilisez Cloud Volumes ONTAP, consultez link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-updating-ontap-cloud.html#supported-upgrade-paths["Mettre à niveau Cloud Volumes ONTAP"] pour obtenir des informations sur la mise à niveau de votre système.

.Avant de commencer
Configurez une machine virtuelle pour Upgrade Health Checker avec les spécifications suivantes :

|===
| Composant | Spécification 


 a| 
*VM*
| Machine virtuelle m5.large ou équivalent avec 2 vCPUs et 8 Gio de RAM 


 a| 
*Système d'exploitation*
| Tout système d'exploitation Linux avec la bibliothèque glibc version 2.28 ou supérieure (Ubuntu 22.04, RHEL8 ou RHEL9) 


 a| 
*Espace disque*
| Au moins 4 Go d'espace libre (8 Go recommandés) dans `/tmp`avec les droits d'exécution 


 a| 
*Réseau*
| Connectivité HTTPS à l'interface logique de gestion (LIF) du ou des clusters ONTAP 


 a| 
*Version ONTAP*
| Cluster exécutant ONTAP 9.11.1 ou version ultérieure 


 a| 
*Conditions d'hébergement*
| Placez la machine virtuelle dans un emplacement disposant d'une connectivité au cluster et d'un accès Internet pour permettre les mises à jour automatiques des outils. La machine doit pouvoir accéder aux points de terminaison suivants via HTTPS (443) pour effectuer les mises à jour automatiques et permettre à NetApp de recevoir des informations AutoSupport sur vos plans de mise à niveau : https://support.netapp.com/[] https://api.uhc.netapp.com[] https://gql.aiq.netapp.com[] https://api.activeiq.netapp.com[] 


 a| 
*Packages recommandés*
| Installez un serveur web pour faciliter l'accès 
|===

NOTE: Assurez-vous que la machine virtuelle puisse se connecter aux points de terminaison de mise à jour automatique et de télémétrie (https://support.netapp.com/[] et https://api.activeiq.netapp.com[] via HTTPS (443) afin de permettre à NetApp de recevoir des informations AutoSupport sur vos plans de mise à niveau. Si vous n'avez pas accès à Internet, vous devez télécharger manuellement la dernière version de Upgrade Health Checker.

.Étapes
. Téléchargez le fichier binaire Upgrade Health Checker en naviguant jusqu'à link:https://console.netapp.com/automationHub["Hub d'automatisation NetApp Console"^] et en trouvant la vignette Upgrade Health Checker.
. Configurez la machine virtuelle Upgrade Health Checker et utilisez SSH pour placer le binaire à l'emplacement de votre choix.
. Vérifiez la signature numérique d'Upgrade Health Checker.
+
Upgrade Health Checker possède un certificat de signature de code public (`UHC-Linux-codesigning-certificate-public.pem`) et une chaîne de certificats intermédiaires et racine (`UHC-Linux-chain-certificates-public.pem`).

+
.. (Facultatif) Vérifiez le certificat de signature de code par rapport à la chaîne :
+
[listing]
----
openssl verify -CAfile UHC-Linux-chain-certificates-public.pem UHC-Linux-codesigning-certificate-public.pem
----
+
Un résultat `OK` confirme une chaîne de confiance valide.

.. Extraire la clé publique du certificat de signature de code :
+
[listing]
----
openssl x509 -in UHC-Linux-codesigning-certificate-public.pem -pubkey -noout -out UHC-Linux-public.pub
----
.. Vérifiez le fichier de signature (`uhc.sig`) par rapport au binaire Upgrade Health Checker à l'aide de la clé publique :
+
[listing]
----
openssl dgst -sha256 -verify UHC-Linux-public.pub -signature uhc.sig uhc
----
+
Un résultat de `Verified OK` confirme que la signature est valide.



. Configurez un compte de service et un rôle pour l'accès au cluster ONTAP. Pour l'accès au cluster via Upgrade Health Checker, créez le rôle de service en tant que rôle REST.
+

NOTE: Vous pouvez créer un playbook Ansible pour automatiser le déploiement du rôle et de l'utilisateur sur tous les clusters ONTAP.

+
Vous devez créer le compte de service pour l'application HTTP. Utilisez les commandes CLI suivantes pour configurer les autorisations nécessaires :

+
[source, cli]
----
security login rest-role create -role uhctool -api /api -access readonly -vserver

security login rest-role create -role uhctool -api /api/support/autosupport -access read_create_modify -vserver

security login rest-role create -role uhctool -api /api/support/autosupport/messages -access read_create_modify -vserver

vserver services web access create -name spi -role uhctool -vserver

security login create -user-or-group-name uhctool -role uhctool -application http -authentication-method password

security login create -user-or-group-name uhctool -role uhctool -application ssh -authentication-method password
----
. (Facultatif) Configurez la gestion des identifiants pour sécuriser l'accès à l'application.
+
Par exemple, si vous avez CyberArk et Conjur, vous pouvez configurer votre environnement pour éviter de transmettre les identifiants via un fichier yaml ou une ligne de commandes.

+
.. Créer les coffres-forts CyberArk requis :
+
... Créez un Safe (Main-Conjur-Safe) qui contient les identifiants et les secrets de l'application
... Créez un Safe (API-Credentials-Safe) qui contient le Conjur Host ID et la clé API
... Créez un Safe (Conjur-SSL-Certificate) contenant le certificat nécessaire


.. Créez les fichiers de configuration (Conjur.conf) et d'identité (Conjur.identity) pour cette application :
+
... Conjur.conf
+
[listing]
----
account:
plugins:[]
appliance_url: https://FQDN
cert_file: /etc/conjur.pem
----
... Conjur.identity
+
[listing]
----
machine https://FQDN/authn
login host /prodvault/devops/<Main-Conjur-Safe>/host1
password XXXXXX
----




+
Voici un exemple d'utilisation de CyberArk et Conjur dans un playbook Ansible :

+
.. Installez Conjur Ansible Collection, qui inclut le Conjur Ansible Lookup Plugin, sur l'hôte Ansible :
+
[listing]
----
ansible-galaxy collection install cyberark.conjur
----
.. Créez une tâche dans un fichier yaml pour récupérer le nom d'utilisateur et le mot de passe depuis CyberArk :
+
[listing]
----
conjur_username: "{{ lookup('cyberark.conjur.conjur_variable', 'prodvault/devops/<Main-Conjur-Safe>/<Account name>/username', validate_certs=false) }}"
conjur_password: "{{ lookup('cyberark.conjur.conjur_variable', 'prodvault/devops/<Main-Conjur-Safe>/<Account name>/password', validate_certs=false) }}"
----




.Informations connexes
* link:upgrade-health-checker-input-parameters.html["Découvrez les paramètres d'entrée pour Upgrade Health Checker"]


.Et ensuite ?
Vous pouvez utiliser Upgrade Health Checker pour vous aider à planifier une mise à niveau ONTAP en link:generate-report-upgrade-health-checker.html["génération d'un rapport de mise à niveau"].
