---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: 'Vous pouvez configurer des e-mails pour recevoir les rapports de vérification de l"état de la mise à niveau.' 
---
= Recevez les rapports de vérification de l'état de la mise à niveau par e-mail
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker peut envoyer des rapports directement dans votre boîte de réception par e-mail. Activez cette fonctionnalité via le fichier config.yaml ou un argument de ligne de commandes. Une fois activée, Upgrade Health Checker envoie les rapports générés (HTML, Excel ou JSON) à un ou plusieurs destinataires via un serveur SMTP. Lorsqu'elle est désactivée, aucun rapport n'est envoyé. Si la génération du rapport échoue et que l'envoi par e-mail est activé, Upgrade Health Checker envoie les fichiers journaux aux destinataires configurés.



[[configure-using-the-config-yaml-file]]
== Configurez à l'aide du fichier config.yaml

Vous pouvez configurer les paramètres de messagerie dans le fichier config.yaml en activant les rapports par e-mail, en ajoutant les détails du serveur SMTP et en spécifiant les adresses des destinataires et les formats de rapport.

. Activez l'envoi de rapports par e-mail dans le fichier config.yaml.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Ajoutez les paramètres de configuration SMTP, les informations de l'expéditeur et l'objet :
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Ajoutez les adresses électroniques des destinataires et définissez les formats de rapports que le système envoie par courriel, par exemple, HTML, EXCEL, JSON ou ALL. Vous pouvez également utiliser l'authentification et le chiffrement :
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== Configurer à l'aide d'arguments de ligne de commandes

Vous pouvez configurer les paramètres de messagerie de base à l'aide d'arguments de ligne de commandes pour activer les rapports, spécifier les destinataires et sélectionner les formats de rapport.

. Activez les rapports par e-mail à l'aide des arguments de ligne de commandes :
+
[listing]
----
./uhc --email-enabled=true
----
. Veuillez fournir les adresses électroniques des destinataires :
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configurez les formats de rapport envoyés par e-mail, par exemple HTML, EXCEL, JSON :
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
Vous pouvez configurer les trois attributs suivants à l'aide d'arguments de ligne de commandes ou du fichier config.yaml. Vous pouvez configurer tous les autres attributs uniquement dans le fichier config.yaml :

* Courriel activé
* Destinataires des courriels
* Formats de rapports par courriel


Notez que les arguments de la ligne de commandes remplacent les valeurs du fichier config.yaml.

Par exemple :

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====