---
sidebar: sidebar 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: Découvrez les nouveautés de ce site de documentation. 
---
= Quoi de neuf dans Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de Upgrade Health Checker. Vous pouvez trouver des informations supplémentaires sur les améliorations en accédant à la vignette Upgrade Health Checker dans le link:https://console.netapp.com/automationHub["Hub d'automatisation NetApp Console"^] et en consultant les derniers fichiers de téléchargement Upgrade Health Checker.



== 15 avril 2026

Cette mise à jour de la documentation Upgrade Health Checker inclut les fonctionnalités suivantes.

* UHC a besoin d'accéder à un nouveau point de terminaison (https://api.activeiq.netapp.com[] pour que les fonctionnalités de mise à jour automatique fonctionnent.
+
link:set-up-upgrade-health-checker.html["Téléchargez et configurez Upgrade Health Checker"].

* UHC propose désormais un nouveau format de rapport (.XLSX - modifiable par l'homme) qui complète les formats HTML (lisible par l'homme) et JSON (lisible par la machine).
+
link:generate-report-upgrade-health-checker.html["Générer un rapport de mise à niveau ONTAP"].

+
link:automate-report-upgrade-health-checker.html["Automatisez la génération de plans de mise à niveau avec Upgrade Health Checker"].





== 13 février 2026

Upgrade Health Checker offre une nouvelle solution pour générer des rapports complets sur site afin de vous permettre de mener à bien une mise à niveau ONTAP. Il peut être utilisé avec les frameworks d'automatisation et d'orchestration existants pour améliorer l'efficacité lors de la mise à niveau d'un ou de plusieurs clusters. Upgrade Health Checker prend en charge les mises à niveau vers ONTAP 9.11.1 et versions ultérieures.

link:learn-about-upgrade-health-checker.html["En savoir plus sur Upgrade Health Checker"].
