---
sidebar: sidebar 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: Découvrez les nouveautés de ce site de documentation. 
---
= Quoi de neuf dans Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de l'outil de vérification de l'état des mises à jour (UHC). Vous pouvez trouver des informations supplémentaires sur les améliorations en accédant à la vignette Upgrade Health Checker dans le link:https://console.netapp.com/automationHub["Hub d'automatisation NetApp Console"^] et en consultant les derniers fichiers de téléchargement Upgrade Health Checker.



[[17-july-2026]]
== 17 juillet 2026

Cette mise à jour ajoute plusieurs améliorations, notamment un tableau de bord de visualisation des risques liés à la flotte, la prise en charge de l'authentification et du chiffrement des e-mails, le rapport du nombre de disques, la prise en charge de la version ONTAP recommandée, ainsi que les vérifications IMT NAS et SAN.

* Tableau de bord UHC : vue *Risque de flotte* maintenant disponible
* Intégration de la messagerie : prise en charge d’un serveur de messagerie avec authentification et chiffrement
* Ajout de *Drive Count* dans le résumé du cluster dans le rapport
* La version ONTAP recommandée est désormais prise en charge
* Ajout de la prise en charge des vérifications IMT pour les NAS et les SAN




[[11-june-2026]]
== 11 juin 2026

Cette mise à jour ajoute la livraison par e-mail des rapports, un paramètre de tableau de bord pour des aperçus rapides de l'état de santé et de nouvelles sections de documentation pour vous aider à maintenir et à dépanner Upgrade Health Checker.

* UHC prend en charge la livraison directe des rapports dans votre boîte de réception.
+
link:setup-email-upgrade-health-checker.html["Recevez les rapports de vérification de l'état de la mise à niveau par e-mail"].

* Introduit le  `--dashboard`paramètre qui régénère le tableau de bord à partir des exécutions existantes à `<runs>/dashboard/index.html`sans contacter un cluster. Il fournit une vue d'ensemble du statut de santé de tous les clusters récemment consultés.
+
link:dashboard-upgrade-health-checker.html["Mise à niveau du tableau de bord Health Checker"], link:upgrade-health-checker-input-parameters.html#dashboard["Paramètre du tableau de bord"].

* Ajout d'une nouvelle section Maintenance, Dépannage et FAQ.
+
** Maintenez Upgrade Health Checker en état de fonctionnement en vérifiant les mises à jour, en surveillant les journaux pour détecter les problèmes récurrents et en vérifiant que vous configurez correctement l'outil.
+
link:maintain-upgrade-health-checker.html["Maintenir le vérificateur de l'état de la mise à niveau"].

** Dépannez les problèmes courants de l'outil de vérification de l'état de la mise à niveau et résolvez les erreurs pouvant bloquer la planification de la mise à niveau ONTAP.
+
link:troubleshoot-upgrade-health-checker.html["Dépannage de la mise à niveau du vérificateur d'état"].

** Foire aux questions (FAQ) pour Upgrade Health Checker.
+
link:faq-upgrade-health-checker.html["FAQ pour le vérificateur d'état de la mise à niveau"].







[[15-april-2026]]
== 15 avril 2026

Cette mise à jour ajoute un nouveau format de rapport XLSX et nécessite l'accès à un nouveau point de terminaison pour que les mises à jour automatiques fonctionnent.

* Vous devez accorder à UHC l'accès à un nouveau point de terminaison (+https://api.activeiq.netapp.com+) pour que les fonctionnalités de mise à jour automatique fonctionnent.
+
link:set-up-upgrade-health-checker.html["Téléchargez et configurez Upgrade Health Checker"].

* UHC propose désormais un nouveau format de rapport (.XLSX - modifiable par l'homme) qui complète les formats HTML (lisible par l'homme) et JSON (lisible par la machine).
+
link:generate-report-upgrade-health-checker.html["Générer un rapport de mise à niveau ONTAP"].

+
link:automate-report-upgrade-health-checker.html["Automatisez la génération de plans de mise à niveau avec Upgrade Health Checker"].





[[13-february-2026]]
== 13 février 2026

Upgrade Health Checker est désormais disponible. Cet outil génère des rapports détaillés, sur site, pour vous aider à mener à bien une mise à niveau d'ONTAP. Vous pouvez utiliser Upgrade Health Checker avec vos frameworks d'automatisation et d'orchestration existants pour gagner du temps lors de la mise à niveau d'un ou de plusieurs clusters. Upgrade Health Checker prend en charge les mises à niveau vers ONTAP 9.11.1 et versions ultérieures.

link:learn-about-upgrade-health-checker.html["En savoir plus sur Upgrade Health Checker"].
